version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
      - chmod +x install-terraform.sh configure-named-profile.sh apply-deployment.sh install-ansible.sh
      - ./install-terraform.sh
      - ./install-ansible.sh
      - ./configure-named-profile.sh
  build:
    commands:
      - ./apply-deployment.sh
      - ansible-playbook -i ./inventory/hosts.cfg site.yml
