version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
      - chmod +x ./install-ansible.sh ./configure-ansible.sh
      - aws secretsmanager get-secret-value --secret-id app-key-pair | jq -r '.SecretString' > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      # Get the public IP of the EC2 instance
      - >
        INSTANCE_IP=$(aws ec2 describe-instances --query "Reservations[*].Instances[*].PublicIpAddress"
        --filters "Name=tag:Name,Values=ansible-control-node" "Name=instance-state-name,Values=running"
        --output text)
  build:
    commands:
      - ssh -o StrictHostKeyChecking=no ec2-user@$INSTANCE_IP 'sudo bash -s' < ./configure-ansible.sh
      - ssh -o StrictHostKeyChecking=no ec2-user@$INSTANCE_IP 'bash -s' < ./install-ansible.sh
