---
- name: Create directory
  file:
    path: /mnt/nfs_shares
    state: directory

- name: Edit exports
  copy:
    dest: /etc/exports
    content: |
      /mnt/nfs_shares 10.26.0.0/24(rw,sync,no_root_squash)

- name: Execute exportfs command
  become: true
  command:
    cmd: sudo exportfs -arv

- name: Configure Selinux
  become: true
  command: sudo setsebool -P nfs_export_all_rw 1
