---
- name: Ensure Python is installed
  ansible.builtin.package:
    name: python3
    state: present

- name: Ensure pip is installed
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install required Python libraries
  ansible.builtin.pip:
    name:
      - boto3
      - botocore
    state: present

- name: Set Python interpreter explicitly
  set_fact:
    ansible_python_interpreter: '/usr/bin/python3'

- name: Gather information about all EFS filesystems
  community.aws.efs_info:
    region: us-east-1
  environment:
    AWS_REGION: us-east-1

- name: Install nfs-common to support NFS
  ansible.builtin.package:
    name: nfs-common
    state: present

- name: Mount EFS filesystems
  ansible.posix.mount:
    path: '/mnt/{{ item.name }}'
    src: '{{ item.dns_name }}:/'
    fstype: 'nfs4'
    opts: 'defaults'
    state: mounted
  loop: '{{ efs_info.efs }}'
  when: efs_info.efs is defined
