---
- name: Gather information about all EFS filesystems
  community.aws.efs_info:
  register: efs_info

- name: Debug - Print EFS Information
  ansible.builtin.debug:
    msg: '{{ efs_info }}'

- name: Install nfs-common to support NFS
  ansible.builtin.package:
    name: nfs-common
    state: present

- name: Mount EFS filesystems
  ansible.posix.mount:
    path: '/mnt/{{ item.name }}'
    src: '{{ item.dns_name }}:/'
    fstype: 'nfs4'
    opts: 'defaults'
    state: mounted
  loop: '{{ efs_info.efs }}'
  when: efs_info.efs is defined
