---
- name: Set Python interpreter explicitly
  set_fact:
    ansible_python_interpreter: '/home/tim/pycharm_projects/django_api_sync/ansible/venv/bin/python3'

- name: Gather information about all EFS filesystems
  community.aws.efs_info:
    region: us-east-1
  environment:
    AWS_REGION: us-east-1

- name: Debug - Print EFS Information
  ansible.builtin.debug:
    msg: '{{ efs_info }}'

- name: Install nfs-common to support NFS
  ansible.builtin.package:
    name: nfs-common
    state: present

- name: Mount EFS filesystems
  ansible.posix.mount:
    path: '/mnt/{{ item.name }}'
    src: '{{ item.dns_name }}:/'
    fstype: 'nfs4'
    opts: 'defaults'
    state: mounted
  loop: '{{ efs_info.efs }}'
  when: efs_info.efs is defined
