---
- name: Install postgre client
  dnf:
    name: postgresql15
    state: present

- name: Install git
  dnf:
    name: git
    state: present

- name: Download Gogs archive from S3
  aws_s3:
    bucket: gogs-artifact
    object: /gogs
    dest: /tmp/gogs
    mode: get

- name: Unpack Gogs archive
  unarchive:
    src: /tmp/gogs_0.13.0_linux_amd64.zip
    dest: /opt
    remote_src: yes
