---
- name: Ensure Python is installed
  ansible.builtin.package:
    name: python3
    state: present

- name: Ensure pip is installed
  pip:
    name: python3-pip
    state: present

- name: Install required Python libraries
  ansible.builtin.pip:
    name:
      - boto3
      - botocore
    extra_args: '--user'

- name: Set Python interpreter explicitly
  set_fact:
    ansible_python_interpreter: '/usr/bin/python3'

- name: Install postgre client
  dnf:
    name: postgresql
    state: present

- name: Install git
  dnf:
    name: git
    state: present

- name: Download Gogs archive
  get_url:
    url: https://dl.gogs.io/0.13.0/gogs_0.13.0_linux_amd64.zip
    dest: /tmp/gogs_0.13.0_linux_amd64.zip

- name: Unpack Gogs archive
  unarchive:
    src: /tmp/gogs_0.13.0_linux_amd64.zip
    dest: /opt
    remote_src: yes
