---
- name: Grant schema access to PostgreSQL user
  postgresql_privs:
    type: schema
    schema: public
    name: gogsapp
    objs: ALL_IN_SCHEMA
    privs: ALL
    database: gogs_db
  become: true
  become_user: postgres

- name: Update pg_hba.conf
  lineinfile:
    path: /var/lib/pgsql/data/pg_hba.conf
    line: 'host    all             all             0.0.0.0/0      md5'
  notify: Restart PostgreSQL

- name: Update postgresql.conf
  lineinfile:
    path: /var/lib/pgsql/data/postgresql.conf
    regexp: '^#?listen_addresses'
    line: "listen_addresses = '*'"
  notify: Restart PostgreSQL
