apiVersion: v1
kind: ConfigMap
metadata:
  name: gogs-config
data:
  app.ini: |
    RUN_USER = root

    [database]
    TYPE     = mysql
    HOST     = mariadb:3306
    NAME     = gogs
    SCHEMA   = public
    USER     = root
    PASSWORD = root
    SSL_MODE = disable

    [repository]
    ROOT           = /app/gogs-repositories
    DEFAULT_BRANCH = master

    [server]
    DOMAIN           = localhost
    HTTP_PORT        = 3000
    EXTERNAL_URL     = http://localhost:3000/
    DISABLE_SSH      = false
    SSH_PORT         = 22
    START_SSH_SERVER = false
    OFFLINE_MODE     = false

    [mailer]
    ENABLED = false

    [auth]
    REQUIRE_EMAIL_CONFIRMATION  = false
    DISABLE_REGISTRATION        = false
    ENABLE_REGISTRATION_CAPTCHA = true
    REQUIRE_SIGNIN_VIEW         = false

    [user]
    ENABLE_EMAIL_NOTIFICATION = false

    [picture]
    DISABLE_GRAVATAR        = false
    ENABLE_FEDERATED_AVATAR = false

    [session]
    PROVIDER = file

    [log]
    MODE      = file
    LEVEL     = Info
    ROOT_PATH = /app/log

    [security]
    INSTALL_LOCK = true
    SECRET_KEY   = cYoMAb3TDSMWgsH

